# Generated by Django 5.2.7 on 2025-10-22 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, help_text='Playback progress in seconds', verbose_name='progress')),
                ('duration', models.IntegerField(default=0, help_text='Total video duration in seconds', verbose_name='duration')),
                ('completed', models.BooleanField(default=False, help_text='Whether the movie was watched completely', verbose_name='completed')),
                ('last_watched', models.DateTimeField(auto_now=True, verbose_name='last watched')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='movies.movie', verbose_name='movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'watch history',
                'verbose_name_plural': 'watch histories',
                'ordering': ['-last_watched'],
                'indexes': [models.Index(fields=['user', '-last_watched'], name='player_watc_user_id_157324_idx'), models.Index(fields=['movie', '-last_watched'], name='player_watc_movie_i_6dbbf8_idx')],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
