version: '3.8'

services:
  video-service:
    build: .
    ports:
      - "8001:8001"
    environment:
      - VIDEO_SERVICE_API_KEY=${VIDEO_SERVICE_API_KEY:-your-secret-api-key}
      - MAX_FILE_SIZE=5368709120
    volumes:
      - ./uploaded_videos:/app/uploaded_videos
      - ./main.py:/app/main.py
    restart: unless-stopped